apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # Name I can give (up to me)
spec:
  replicas: 1 # This gives us how many of pods we want to deploy
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers: # Specifies containers as in Docker
        - name: nginx
          image: nginx:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---  # This separates different specifications in one file

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer # distributes trafics between deployments/pods
  selector:
    app: nginx-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80 # for actual domain so we dont care about putting port inside url
    targetPort: 80
