apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment # Name I can give (up to me)
spec:
  replicas: 1 # This gives us how many of pods we want to deploy
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers: # Specifies containers as in Docker
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"