apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer # distributes trafics between deployments/pods
  selector:
    app: nginx-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80 # for actual domain so we dont care about putting port inside url
    targetPort: 80
