apiVersion: apps/v1
kind: Deployment
metadata:
  name: iac-python-deployment # Name I can give (up to me)
spec:
  replicas: 3 # This gives us how many of pods we want to deploy
  selector:
    matchLabels:
      app: iac-python-deployment
  template:
    metadata:
      labels:
        app: iac-python-deployment
    spec:
      containers: # Specifies containers as in Docker
        - name: iac-python
          image: codingforentrepreneurs/iac-python:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PORT
              value: "8181"
          ports:
            - containerPort: 8181

---

apiVersion: v1
kind: Service
metadata:
  name: iac-python-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: LoadBalancer # distributes trafics between deployments/pods NOT WORKING ON okteto
  selector:
    app: iac-python-deployment
  ports:
  - name: http
    protocol: TCP
    port: 80 # for actual domain so we dont care about putting port inside url
    targetPort: 8181
